# Generated by Django 5.2 on 2025-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangalorejobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
