# Generated by Django 5.2 on 2025-09-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_alter_bangalorejobs_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('eligibility', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bangalorejobs',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='Phonenumber',
            field=models.IntegerField(),
        ),
    ]
