# Generated by Django 5.2 on 2025-09-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0003_chennaijobs_alter_bangalorejobs_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangalorejobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
