# Generated by Django 5.2 on 2025-09-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0004_alter_bangalorejobs_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chennaijobs',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
